# Generated by Django 4.1.7 on 2023-05-03 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_username_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default=datetime.datetime(2023, 5, 3, 10, 11, 29, 226466, tzinfo=datetime.timezone.utc), max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
