name: build_main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Write GitHub environment variables to .env
      run: |
        echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> ${{ github.workspace }}/.env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> ${{ github.workspace }}/.env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> ${{ github.workspace }}/.env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> ${{ github.workspace }}/.env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> ${{ github.workspace }}/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> ${{ github.workspace }}/.env
        echo "EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }}" >> ${{ github.workspace }}/.env
        echo "EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }}" >> ${{ github.workspace }}/.env
        echo "KHALTI_PUBLIC_KET=${{ secrets.KHALTI_PUBLIC_KET }}" >> ${{ github.workspace }}/.env
        echo "KHALTI_SECRET_KET=${{ secrets.KHALTI_SECRET_KET }}" >> ${{ github.workspace }}/.env
    - name: Set permissions 
      run: sudo chmod -R 777 ${{ github.workspace }}
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Start docker container
      run: |
        sudo docker-compose up -d ourcart
