name: build_main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Set permissions 
      run: sudo chmod -R 777 ${{ github.workspace }}
    - name: 'Create env file'
      run: |
        echo "DB_DATABASE=${DB_DATABASE}" | sudo tee ${{ github.workspace }}/.env
        echo "DB_HOST=${DB_HOST}" | sudo tee -a ${{ github.workspace }}/.env
        echo "DB_PASSWORD=${DB_PASSWORD}" | sudo tee -a ${{ github.workspace }}/.env
        echo "DB_PORT=${DB_PORT}" | sudo tee -a ${{ github.workspace }}/.env
        echo "DB_USER=${DB_USER}" | sudo tee -a ${{ github.workspace }}/.env
        echo "EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}" | sudo tee -a ${{ github.workspace }}/.env
        echo "EMAIL_HOST_USER=${EMAIL_HOST_USER}" | sudo tee -a ${{ github.workspace }}/.env
        echo "KHALTI_PUBLIC_KEY=${KHALTI_PUBLIC_KEY}" | sudo tee -a ${{ github.workspace }}/.env
        echo "KHALTI_SECRET_KEY=${KHALTI_SECRET_KEY}" | sudo tee -a ${{ github.workspace }}/.env
    
    - name: Debug .env File
      run: cat .env

    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Start docker container
      run: |
        sudo docker-compose up -d ourcart
