name: build_main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  CI: true

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Set permissions 
      run: sudo chmod -R 777 ${{ github.workspace }}
    - name: 'Create env file'
      run: |
    - name: create env file
      run: |
             touch .env
             echo DB_DATABASE=${{ secrets.DB_DATABASE }} >> .env
        
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Start docker container
      run: |
        sudo docker-compose up -d ourcart
