name: build_main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code for deployment
      uses: actions/checkout@v3
      
    - name: Create .env file
      run: |
        echo "${{ vars.ENV }}" > .env
      
    - name: deploy using rsync
      uses: burnett01/rsync-deployments@master
      with:
        switches: -avzr --delete 
        path: ./
        remote_path: /home/azureuser/sudarshan/Ecommerce-Django
        remote_host: ${{ secrets.HOST }}
        remote_user: ${{ secrets.USERNAME }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
  
    - name: restart uvicorn service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
            cd /home/azureuser/sudarshan/
            source /home/azureuser/sudarshan/ourcart_env/bin/activate
            cd /home/azureuser/sudarshan/Ecommerce-Django
            pip install -r requirements.txt
            deactivate
            sudo systemctl restart ourcart.socket
            sudo systemctl restart ourcart.service
