name: build_main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Write GitHub environment variables to .env
      run: echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> ${{ github.workspace }}/.env
    - name: Set permissions 
      run: sudo chmod -R 777 ${{ github.workspace }}
    - uses: actions/checkout@v3
    # - run: cat .env >> $GITHUB_ENV
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        # python -m pip install --upgrade pip
        # pip install -r requirements.txt
        sudo docker-compose up -d ourcart
    # - name: Run application
    #   run: |
    #     python manage.py runserver
    - name: Debugging
      run: |
        ls -la ${{ github.workspace }}
        echo "Current working directory: $(pwd)"
        echo "Contents of the directory: $(ls)"
        echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> ${{ github.workspace }}/.env
        cat ${{ github.workspace }}/.env
