name: create a comment in new issue

on:
  issues:
    types: [opened]

jobs:
  when-issue-opened:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github content"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
        
      
